// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketManagementSystem.Models;

namespace TicketManagementSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20191105065847_CartLine")]
    partial class CartLine
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TicketManagementSystem.Models.Cart", b =>
                {
                    b.Property<int>("c_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Date")
                        .IsRequired();

                    b.Property<int?>("Promopr_Id");

                    b.Property<int?>("Useru_Id");

                    b.Property<string>("totalTk")
                        .IsRequired();

                    b.HasKey("c_Id");

                    b.HasIndex("Promopr_Id");

                    b.HasIndex("Useru_Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("TicketManagementSystem.Models.CartLine", b =>
                {
                    b.Property<int>("ct_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Cartc_Id");

                    b.Property<string>("Catarory")
                        .IsRequired();

                    b.Property<int?>("CavinDetailscv_Id");

                    b.Property<string>("Price")
                        .IsRequired();

                    b.HasKey("ct_Id");

                    b.HasIndex("Cartc_Id");

                    b.HasIndex("CavinDetailscv_Id");

                    b.ToTable("CartLines");
                });

            modelBuilder.Entity("TicketManagementSystem.Models.CavinDetails", b =>
                {
                    b.Property<int>("cv_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CavinCatagory")
                        .IsRequired();

                    b.Property<string>("CavinNumber")
                        .IsRequired();

                    b.Property<int?>("Launchl_Id");

                    b.Property<string>("Position")
                        .IsRequired();

                    b.Property<double>("Rent");

                    b.HasKey("cv_Id");

                    b.HasIndex("Launchl_Id");

                    b.ToTable("CavinDetails");
                });

            modelBuilder.Entity("TicketManagementSystem.Models.FeedBack", b =>
                {
                    b.Property<int>("fb_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Cartc_Id");

                    b.Property<string>("Details")
                        .IsRequired();

                    b.Property<string>("Filter")
                        .IsRequired();

                    b.Property<int?>("Useru_Id");

                    b.HasKey("fb_Id");

                    b.HasIndex("Cartc_Id");

                    b.HasIndex("Useru_Id");

                    b.ToTable("FeedBacks");
                });

            modelBuilder.Entity("TicketManagementSystem.Models.Launch", b =>
                {
                    b.Property<int>("l_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Rout")
                        .IsRequired();

                    b.HasKey("l_Id");

                    b.ToTable("Launches");
                });

            modelBuilder.Entity("TicketManagementSystem.Models.Owner", b =>
                {
                    b.Property<int>("o_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<int?>("Launchl_Id");

                    b.Property<string>("Phone")
                        .IsRequired();

                    b.Property<string>("ownerName")
                        .IsRequired();

                    b.HasKey("o_Id");

                    b.HasIndex("Launchl_Id");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("TicketManagementSystem.Models.Payment", b =>
                {
                    b.Property<int>("p_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Cartc_Id");

                    b.Property<string>("PaymentOption")
                        .IsRequired();

                    b.Property<string>("PaymentStatus")
                        .IsRequired();

                    b.Property<int?>("Useru_Id");

                    b.HasKey("p_Id");

                    b.HasIndex("Cartc_Id");

                    b.HasIndex("Useru_Id");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("TicketManagementSystem.Models.Promo", b =>
                {
                    b.Property<int>("pr_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discount")
                        .IsRequired();

                    b.Property<DateTime>("EndDate");

                    b.Property<double>("MaxAmount");

                    b.Property<string>("PromoCode")
                        .IsRequired();

                    b.Property<DateTime>("StartDate");

                    b.HasKey("pr_Id");

                    b.ToTable("Promos");
                });

            modelBuilder.Entity("TicketManagementSystem.Models.PromoForLaunch", b =>
                {
                    b.Property<int>("pfl_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Promopr_Id");

                    b.Property<int?>("Useru_Id");

                    b.HasKey("pfl_id");

                    b.HasIndex("Promopr_Id");

                    b.HasIndex("Useru_Id");

                    b.ToTable("PromoForLaunches");
                });

            modelBuilder.Entity("TicketManagementSystem.Models.PromoForUser", b =>
                {
                    b.Property<int>("pfu_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Launchl_Id");

                    b.Property<int?>("Promopr_Id");

                    b.HasKey("pfu_id");

                    b.HasIndex("Launchl_Id");

                    b.HasIndex("Promopr_Id");

                    b.ToTable("PromoForUsers");
                });

            modelBuilder.Entity("TicketManagementSystem.Models.PromoUser", b =>
                {
                    b.Property<int>("pu_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Date")
                        .IsRequired();

                    b.Property<int?>("Promopr_Id");

                    b.Property<string>("Time")
                        .IsRequired();

                    b.Property<int?>("Useru_Id");

                    b.HasKey("pu_Id");

                    b.HasIndex("Promopr_Id");

                    b.HasIndex("Useru_Id");

                    b.ToTable("PromoUsers");
                });

            modelBuilder.Entity("TicketManagementSystem.Models.Schedul", b =>
                {
                    b.Property<int>("s_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Date")
                        .IsRequired();

                    b.Property<string>("From")
                        .IsRequired();

                    b.Property<int?>("Launchl_Id");

                    b.Property<string>("Time")
                        .IsRequired();

                    b.Property<string>("To")
                        .IsRequired();

                    b.HasKey("s_Id");

                    b.HasIndex("Launchl_Id");

                    b.ToTable("Scheduls");
                });

            modelBuilder.Entity("TicketManagementSystem.Models.User", b =>
                {
                    b.Property<int>("u_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Gender")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Password")
                        .HasMaxLength(16);

                    b.Property<string>("Phone")
                        .IsRequired();

                    b.HasKey("u_Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TicketManagementSystem.Models.Cart", b =>
                {
                    b.HasOne("TicketManagementSystem.Models.Promo", "Promo")
                        .WithMany()
                        .HasForeignKey("Promopr_Id");

                    b.HasOne("TicketManagementSystem.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("Useru_Id");
                });

            modelBuilder.Entity("TicketManagementSystem.Models.CartLine", b =>
                {
                    b.HasOne("TicketManagementSystem.Models.Cart", "Cart")
                        .WithMany()
                        .HasForeignKey("Cartc_Id");

                    b.HasOne("TicketManagementSystem.Models.CavinDetails", "CavinDetails")
                        .WithMany()
                        .HasForeignKey("CavinDetailscv_Id");
                });

            modelBuilder.Entity("TicketManagementSystem.Models.CavinDetails", b =>
                {
                    b.HasOne("TicketManagementSystem.Models.Launch", "Launch")
                        .WithMany()
                        .HasForeignKey("Launchl_Id");
                });

            modelBuilder.Entity("TicketManagementSystem.Models.FeedBack", b =>
                {
                    b.HasOne("TicketManagementSystem.Models.Cart", "Cart")
                        .WithMany()
                        .HasForeignKey("Cartc_Id");

                    b.HasOne("TicketManagementSystem.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("Useru_Id");
                });

            modelBuilder.Entity("TicketManagementSystem.Models.Owner", b =>
                {
                    b.HasOne("TicketManagementSystem.Models.Launch", "Launch")
                        .WithMany()
                        .HasForeignKey("Launchl_Id");
                });

            modelBuilder.Entity("TicketManagementSystem.Models.Payment", b =>
                {
                    b.HasOne("TicketManagementSystem.Models.Cart", "Cart")
                        .WithMany()
                        .HasForeignKey("Cartc_Id");

                    b.HasOne("TicketManagementSystem.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("Useru_Id");
                });

            modelBuilder.Entity("TicketManagementSystem.Models.PromoForLaunch", b =>
                {
                    b.HasOne("TicketManagementSystem.Models.Promo", "Promo")
                        .WithMany()
                        .HasForeignKey("Promopr_Id");

                    b.HasOne("TicketManagementSystem.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("Useru_Id");
                });

            modelBuilder.Entity("TicketManagementSystem.Models.PromoForUser", b =>
                {
                    b.HasOne("TicketManagementSystem.Models.Launch", "Launch")
                        .WithMany()
                        .HasForeignKey("Launchl_Id");

                    b.HasOne("TicketManagementSystem.Models.Promo", "Promo")
                        .WithMany()
                        .HasForeignKey("Promopr_Id");
                });

            modelBuilder.Entity("TicketManagementSystem.Models.PromoUser", b =>
                {
                    b.HasOne("TicketManagementSystem.Models.Promo", "Promo")
                        .WithMany()
                        .HasForeignKey("Promopr_Id");

                    b.HasOne("TicketManagementSystem.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("Useru_Id");
                });

            modelBuilder.Entity("TicketManagementSystem.Models.Schedul", b =>
                {
                    b.HasOne("TicketManagementSystem.Models.Launch", "Launch")
                        .WithMany()
                        .HasForeignKey("Launchl_Id");
                });
#pragma warning restore 612, 618
        }
    }
}
